name: Build and Test
agent:
  type: Unity::VM
  image: sdet/gamecode_win10:v0.2.1-91595
  flavor: m1.large
  name: Validate a Package in CI
commands:
  - npm install upm-ci-utils -g --registry https://api.bintray.com/npm/unity/unity-npm
  # Add your custom build commands here
  - upm-ci package pack --package-path .
  - upm-ci package test --editor-revision asf234sdf234sadf234 --package-path .
triggers:
  branches:
    only:
      - master
  tags:
    only:
      - /(p|P)ublish/
artifacts:
  Package.zip:
    paths:
      - "automation/packages/com.unity.packages-starter-kit-1.0.0-preview.tgz"
  TestResults.zip:
    paths:
      - "my-project/automation/test-results/*"
  EditorLogs.zip:
    paths:
      - "my-project/automation/logs/*"
